// Map team name -> ISO 3166-1 alpha-2 code, then to flag emoji.
const ISO: Record<string, string> = {
  "Canada": "CA",
  "Mexico": "MX",
  "United States": "US",
  "USA": "US",
  "Argentina": "AR",
  "Brazil": "BR",
  "Uruguay": "UY",
  "Colombia": "CO",
  "Ecuador": "EC",
  "Paraguay": "PY",
  "Chile": "CL",
  "Peru": "PE",
  "Venezuela": "VE",
  "Bolivia": "BO",
  "France": "FR",
  "England": "GB-ENG",
  "Spain": "ES",
  "Germany": "DE",
  "Portugal": "PT",
  "Netherlands": "NL",
  "Belgium": "BE",
  "Bosnia and Herzegovina": "BA",
  "Bosnia-Herzegovina": "BA",
  "Italy": "IT",
  "Croatia": "HR",
  "Switzerland": "CH",
  "Denmark": "DK",
  "Austria": "AT",
  "Poland": "PL",
  "Norway": "NO",
  "Sweden": "SE",
  "Serbia": "RS",
  "Turkey": "TR",
  "Türkiye": "TR",
  "Turkiye": "TR",
  "Wales": "GB-WLS",
  "Scotland": "GB-SCT",
  "Republic of Ireland": "IE",
  "Ireland": "IE",
  "Ukraine": "UA",
  "Czechia": "CZ",
  "DR Congo": "CD",
  "Hungary": "HU",
  "Romania": "RO",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "Greece": "GR",
  "Albania": "AL",
  "Japan": "JP",
  "South Korea": "KR",
  "Korea Republic": "KR",
  "Iran": "IR",
  "IR Iran": "IR",
  "Saudi Arabia": "SA",
  "Qatar": "QA",
  "Australia": "AU",
  "Uzbekistan": "UZ",
  "Jordan": "JO",
  "Iraq": "IQ",
  "United Arab Emirates": "AE",
  "UAE": "AE",
  "Morocco": "MA",
  "Senegal": "SN",
  "Tunisia": "TN",
  "Algeria": "DZ",
  "Egypt": "EG",
  "Nigeria": "NG",
  "Ghana": "GH",
  "Cameroon": "CM",
  "Ivory Coast": "CI",
  "Côte d'Ivoire": "CI",
  "South Africa": "ZA",
  "Cape Verde": "CV",
  "New Zealand": "NZ",
  "Costa Rica": "CR",
  "Panama": "PA",
  "Jamaica": "JM",
  "Honduras": "HN",
  "El Salvador": "SV",
  "Curaçao": "CW",
  "Curacao": "CW",
  "Haiti": "HT",
  "Trinidad and Tobago": "TT",
};

const SUBDIVISION_FLAG: Record<string, string> = {
  // Tag sequence flags for England/Scotland/Wales
  "GB-ENG": "\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}",
  "GB-SCT": "\u{1F3F4}\u{E0067}\u{E0062}\u{E0073}\u{E0063}\u{E0074}\u{E007F}",
  "GB-WLS": "\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}",
};

export function flagFor(team: string): string {
  const code = ISO[team.trim()];
  if (!code) return "";
  if (SUBDIVISION_FLAG[code]) return SUBDIVISION_FLAG[code];
  if (code.length !== 2) return "";
  const A = 0x1f1e6;
  const a = "A".charCodeAt(0);
  return String.fromCodePoint(A + (code.charCodeAt(0) - a), A + (code.charCodeAt(1) - a));
}