/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMyPredictionsRouteImport } from './routes/_authenticated/my-predictions'
import { Route as AuthenticatedLuckboxRouteImport } from './routes/_authenticated/luckbox'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicSyncResultsRouteImport } from './routes/api/public/sync-results'
import { Route as ApiPublicHooksSyncFixtureGoalsRouteImport } from './routes/api/public/hooks/sync-fixture-goals'
import { Route as ApiPublicHooksRefreshTeamFormRouteImport } from './routes/api/public/hooks/refresh-team-form'
import { Route as ApiPublicHooksRefreshHighlightsRouteImport } from './routes/api/public/hooks/refresh-highlights'
import { Route as ApiPublicHooksRefreshCsOddsRouteImport } from './routes/api/public/hooks/refresh-cs-odds'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyPredictionsRoute =
  AuthenticatedMyPredictionsRouteImport.update({
    id: '/my-predictions',
    path: '/my-predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLuckboxRoute = AuthenticatedLuckboxRouteImport.update({
  id: '/luckbox',
  path: '/luckbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSyncResultsRoute = ApiPublicSyncResultsRouteImport.update({
  id: '/api/public/sync-results',
  path: '/api/public/sync-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncFixtureGoalsRoute =
  ApiPublicHooksSyncFixtureGoalsRouteImport.update({
    id: '/api/public/hooks/sync-fixture-goals',
    path: '/api/public/hooks/sync-fixture-goals',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshTeamFormRoute =
  ApiPublicHooksRefreshTeamFormRouteImport.update({
    id: '/api/public/hooks/refresh-team-form',
    path: '/api/public/hooks/refresh-team-form',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshHighlightsRoute =
  ApiPublicHooksRefreshHighlightsRouteImport.update({
    id: '/api/public/hooks/refresh-highlights',
    path: '/api/public/hooks/refresh-highlights',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshCsOddsRoute =
  ApiPublicHooksRefreshCsOddsRouteImport.update({
    id: '/api/public/hooks/refresh-cs-odds',
    path: '/api/public/hooks/refresh-cs-odds',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/luckbox': typeof AuthenticatedLuckboxRoute
  '/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
  '/api/public/hooks/refresh-cs-odds': typeof ApiPublicHooksRefreshCsOddsRoute
  '/api/public/hooks/refresh-highlights': typeof ApiPublicHooksRefreshHighlightsRoute
  '/api/public/hooks/refresh-team-form': typeof ApiPublicHooksRefreshTeamFormRoute
  '/api/public/hooks/sync-fixture-goals': typeof ApiPublicHooksSyncFixtureGoalsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/luckbox': typeof AuthenticatedLuckboxRoute
  '/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
  '/api/public/hooks/refresh-cs-odds': typeof ApiPublicHooksRefreshCsOddsRoute
  '/api/public/hooks/refresh-highlights': typeof ApiPublicHooksRefreshHighlightsRoute
  '/api/public/hooks/refresh-team-form': typeof ApiPublicHooksRefreshTeamFormRoute
  '/api/public/hooks/sync-fixture-goals': typeof ApiPublicHooksSyncFixtureGoalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/luckbox': typeof AuthenticatedLuckboxRoute
  '/_authenticated/my-predictions': typeof AuthenticatedMyPredictionsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/sync-results': typeof ApiPublicSyncResultsRoute
  '/api/public/hooks/refresh-cs-odds': typeof ApiPublicHooksRefreshCsOddsRoute
  '/api/public/hooks/refresh-highlights': typeof ApiPublicHooksRefreshHighlightsRoute
  '/api/public/hooks/refresh-team-form': typeof ApiPublicHooksRefreshTeamFormRoute
  '/api/public/hooks/sync-fixture-goals': typeof ApiPublicHooksSyncFixtureGoalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/leaderboard'
    | '/luckbox'
    | '/my-predictions'
    | '/api/public/sync-results'
    | '/api/public/hooks/refresh-cs-odds'
    | '/api/public/hooks/refresh-highlights'
    | '/api/public/hooks/refresh-team-form'
    | '/api/public/hooks/sync-fixture-goals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/leaderboard'
    | '/luckbox'
    | '/my-predictions'
    | '/'
    | '/api/public/sync-results'
    | '/api/public/hooks/refresh-cs-odds'
    | '/api/public/hooks/refresh-highlights'
    | '/api/public/hooks/refresh-team-form'
    | '/api/public/hooks/sync-fixture-goals'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/leaderboard'
    | '/_authenticated/luckbox'
    | '/_authenticated/my-predictions'
    | '/_authenticated/'
    | '/api/public/sync-results'
    | '/api/public/hooks/refresh-cs-odds'
    | '/api/public/hooks/refresh-highlights'
    | '/api/public/hooks/refresh-team-form'
    | '/api/public/hooks/sync-fixture-goals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicSyncResultsRoute: typeof ApiPublicSyncResultsRoute
  ApiPublicHooksRefreshCsOddsRoute: typeof ApiPublicHooksRefreshCsOddsRoute
  ApiPublicHooksRefreshHighlightsRoute: typeof ApiPublicHooksRefreshHighlightsRoute
  ApiPublicHooksRefreshTeamFormRoute: typeof ApiPublicHooksRefreshTeamFormRoute
  ApiPublicHooksSyncFixtureGoalsRoute: typeof ApiPublicHooksSyncFixtureGoalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-predictions': {
      id: '/_authenticated/my-predictions'
      path: '/my-predictions'
      fullPath: '/my-predictions'
      preLoaderRoute: typeof AuthenticatedMyPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/luckbox': {
      id: '/_authenticated/luckbox'
      path: '/luckbox'
      fullPath: '/luckbox'
      preLoaderRoute: typeof AuthenticatedLuckboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sync-results': {
      id: '/api/public/sync-results'
      path: '/api/public/sync-results'
      fullPath: '/api/public/sync-results'
      preLoaderRoute: typeof ApiPublicSyncResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-fixture-goals': {
      id: '/api/public/hooks/sync-fixture-goals'
      path: '/api/public/hooks/sync-fixture-goals'
      fullPath: '/api/public/hooks/sync-fixture-goals'
      preLoaderRoute: typeof ApiPublicHooksSyncFixtureGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-team-form': {
      id: '/api/public/hooks/refresh-team-form'
      path: '/api/public/hooks/refresh-team-form'
      fullPath: '/api/public/hooks/refresh-team-form'
      preLoaderRoute: typeof ApiPublicHooksRefreshTeamFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-highlights': {
      id: '/api/public/hooks/refresh-highlights'
      path: '/api/public/hooks/refresh-highlights'
      fullPath: '/api/public/hooks/refresh-highlights'
      preLoaderRoute: typeof ApiPublicHooksRefreshHighlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-cs-odds': {
      id: '/api/public/hooks/refresh-cs-odds'
      path: '/api/public/hooks/refresh-cs-odds'
      fullPath: '/api/public/hooks/refresh-cs-odds'
      preLoaderRoute: typeof ApiPublicHooksRefreshCsOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedLuckboxRoute: typeof AuthenticatedLuckboxRoute
  AuthenticatedMyPredictionsRoute: typeof AuthenticatedMyPredictionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedLuckboxRoute: AuthenticatedLuckboxRoute,
  AuthenticatedMyPredictionsRoute: AuthenticatedMyPredictionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicSyncResultsRoute: ApiPublicSyncResultsRoute,
  ApiPublicHooksRefreshCsOddsRoute: ApiPublicHooksRefreshCsOddsRoute,
  ApiPublicHooksRefreshHighlightsRoute: ApiPublicHooksRefreshHighlightsRoute,
  ApiPublicHooksRefreshTeamFormRoute: ApiPublicHooksRefreshTeamFormRoute,
  ApiPublicHooksSyncFixtureGoalsRoute: ApiPublicHooksSyncFixtureGoalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
